package infosistema.openbaas.rest;

import infosistema.openbaas.middleLayer.AppsMiddleLayer;
import infosistema.openbaas.middleLayer.SessionMiddleLayer;
import infosistema.openbaas.middleLayer.UsersMiddleLayer;
import infosistema.openbaas.data.Error;
import infosistema.openbaas.data.Metadata;
import infosistema.openbaas.data.Result;
import infosistema.openbaas.data.enums.ModelEnum;
import infosistema.openbaas.data.models.User;
import infosistema.openbaas.rest.AppResource.PATCH;
import infosistema.openbaas.utils.Const;
import infosistema.openbaas.utils.Log;
import infosistema.openbaas.utils.Utils;
import infosistema.openbaas.utils.encryption.PasswordEncryptionService;

import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.List;
import java.util.Map.Entry;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.Cookie;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.core.Response.Status;

import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;


public class AccountResource {

	private UsersMiddleLayer usersMid;
	private SessionMiddleLayer sessionMid;
	private AppsMiddleLayer appsMid;
	private String appId;


	@Context
	UriInfo uriInfo;


	public AccountResource(String appId) {
		this.usersMid = UsersMiddleLayer.getInstance();
		this.appId = appId;
		this.sessionMid = SessionMiddleLayer.getInstance();
		this.appsMid = AppsMiddleLayer.getInstance();
	}

	// *** CREATE *** //

	/**
	 * Creates a user in the application, necessary fields: "password";
	 * and "email". signin the user creating a session
	 * 
	 * @param inputJsonObj
	 * @return
	 */
	@Path("/signup")
	@POST
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response createUserAndLogin(JSONObject inputJsonObj, @Context UriInfo ui, @Context HttpHeaders hh) {
		Response response = null;
		MultivaluedMap<String, String> headerParams = hh.getRequestHeaders();
		String email = null;
		String userName = null;
		String password = null;
		Boolean baseLocationOption = null;
		String baseLocation = null;
		String userFile = null;
		String userId = null;
		String appKey = null;
		Boolean readOk = false;
		String location = null;
		List<String> locationList = null;
		for (Entry<String, List<String>> entry : headerParams.entrySet()) {
			if (entry.getKey().equalsIgnoreCase(Const.LOCATION))
				locationList = entry.getValue();
			if (entry.getKey().equalsIgnoreCase(Const.APP_KEY))
				appKey = entry.getValue().get(0);
		}
		if(appKey==null)
			return Response.status(Status.BAD_REQUEST).entity("App Key not found").build();
		if(!appsMid.authenticateApp(appId,appKey))
			return Response.status(Status.UNAUTHORIZED).entity("Wrong App Key").build();
		if (locationList != null)
			location = locationList.get(0);
		try {
			userName = (String) inputJsonObj.opt("userName");
			userFile = (String) inputJsonObj.opt("userFile");
			email = (String) inputJsonObj.get("email");
			password = (String) inputJsonObj.get("password");
				baseLocationOption = (Boolean) inputJsonObj.opt("baseLocationOption");
				baseLocation = (String) inputJsonObj.opt("baseLocation");
			readOk = true;
		} catch (JSONException e) {
			Log.error("", this, "createUserAndLogin", "Error parsing the JSON.", e); 
			return Response.status(Status.BAD_REQUEST).entity("Error parsing the JSON.").build();
		}
		if (userName == null) {
			userName = email;
		}
		if(!AppsMiddleLayer.getInstance().appExists(appId))
			return Response.status(Status.NOT_FOUND).entity("{\"App\": "+appId+"}").build();
		if (readOk) {
			if (!usersMid.userExistsInApp(appId, userId, email)) {
				if (uriInfo == null) 
					uriInfo=ui;
					User outUser = usersMid.createUserAndLogin(headerParams, ui,appId, userName, email, password, userFile,baseLocationOption, baseLocation);
				Metadata meta = usersMid.createMetadata(appId, outUser.getUserId(), null, outUser.getUserId(), ModelEnum.users, location);
				Result res = new Result(outUser, meta);
				response = Response.status(Status.CREATED).entity(res).build();
			} else {
				response = Response.status(Status.FORBIDDEN).entity(new Error("{\"email exists\": "+email+"}")).build();
			}
		} else {
			response = Response.status(Status.BAD_REQUEST).entity(new Error("")).build();
		}
		return response;
	}

	/**
	 * Creates a user session and returns de session Identifier (generated by
	 * the server). Required fields: "email", "password".
	 * 
	 * @param req
	 * @param inputJsonObj
	 * @return
	 */
	@Path("/signin")
	@POST
	@Consumes({ MediaType.APPLICATION_JSON })
	@Produces(MediaType.APPLICATION_JSON)
	public Response createSession(@Context HttpServletRequest req, JSONObject inputJsonObj, @Context UriInfo ui, @Context HttpHeaders hh) {
		MultivaluedMap<String, String> headerParams = hh.getRequestHeaders();
		String email = null; // user inserted fields
		String attemptedPassword = null; // user inserted fields
		Response response = null;
		User outUser = new User();
		List<String> locationList = null;
		List<String> userAgentList = null;
		String userAgent = null;
		String location = null;
		String appKey = null;
		Boolean refreshCode = false;

		try {
			email = (String) inputJsonObj.get("email");
			attemptedPassword = (String) inputJsonObj.get("password");
		} catch (JSONException e) {
			Log.error("", this, "createSession", "Error parsing the JSON.", e); 
			return Response.status(Status.BAD_REQUEST).entity(new Error("Error reading JSON")).build();
		}
		for (Entry<String, List<String>> entry : headerParams.entrySet()) {
			if (entry.getKey().equalsIgnoreCase(Const.LOCATION))
				locationList = entry.getValue();
			if (entry.getKey().equalsIgnoreCase("user-agent"))
				userAgentList = entry.getValue();	
			if (entry.getKey().equalsIgnoreCase(Const.APP_KEY))
				appKey = entry.getValue().get(0);
		}
		if(appKey==null)
			return Response.status(Status.BAD_REQUEST).entity("App Key not found").build();
		if(!appsMid.authenticateApp(appId,appKey))
			return Response.status(Status.UNAUTHORIZED).entity("Wrong App Key").build();
		if (locationList != null)
			location = locationList.get(0);
		if (userAgentList != null)
			userAgent = userAgentList.get(0);
		//// String email = usersMid.getEmailUsingUserName(appId, userName);
		if(email == null && attemptedPassword == null)
			return Response.status(Status.BAD_REQUEST).entity("Error reading JSON").build();
		outUser = usersMid.getUserUsingEmail(appId, email);
		if (outUser.getUserId() != null) {
			boolean usersConfirmedOption = usersMid.getConfirmUsersEmailOption(appId);
			// Remember the order of evaluation in java
			if (usersConfirmedOption) {
				if (usersMid.userEmailIsConfirmed(appId, outUser.getUserId())) {
					String sessionToken = Utils.getRandomString(Const.getIdLength());
					boolean validation = sessionMid.createSession(sessionToken, appId, outUser.getUserId(), attemptedPassword);
					sessionMid.refreshSession(sessionToken, location, userAgent);
					refreshCode = true;
					if (validation && refreshCode) {
						outUser.setUserID(outUser.getUserId());
						outUser.setReturnToken(sessionToken);
						outUser.setUserEmail(email);
						outUser.setUserName(outUser.getUserName());
						outUser.setUserFile(outUser.getUserFile());
						Metadata meta = usersMid.createMetadata(appId, outUser.getUserId(), null, outUser.getUserId(), ModelEnum.users, location);
						Result res = new Result(outUser, meta);
						response = Response.status(Status.OK).entity(res).build();
					}
				} else {
					response = Response.status(Status.FORBIDDEN).entity(new Error(Const.getEmailConfirmationError())).build();
				}
			} else{
				Log.debug("", this, "createSession", "userId of email: " + email + " is: " + outUser.getUserId());
				String sessionToken = Utils.getRandomString(Const.getIdLength());
				boolean validation = sessionMid.createSession(sessionToken, appId, outUser.getUserId(), attemptedPassword);
				if(validation){
					sessionMid.refreshSession(sessionToken, location, userAgent);
					refreshCode = true;
					if (validation && refreshCode) {
						outUser.setUserID(outUser.getUserId());
						outUser.setReturnToken(sessionToken);
						outUser.setUserEmail(email);
						outUser.setUserName(outUser.getUserName());
						outUser.setUserFile(outUser.getUserFile());
						Metadata meta = usersMid.createMetadata(appId, outUser.getUserId(), null, outUser.getUserId(), ModelEnum.users, location);
						Result res = new Result(outUser, meta);
						response = Response.status(Status.OK).entity(res).build();
					}
				}else
					response = Response.status(Status.UNAUTHORIZED).entity(new Error("")).build();				
			}
		} else
			response = Response.status(Status.NOT_FOUND).entity(new Error("")).build();
		return response;

	}


	// *** UPDATE *** //

	@PATCH
	@Path("/sessions/{sessionToken}")
	@Consumes({ MediaType.APPLICATION_JSON })
	public Response patchSession( @HeaderParam("user-agent") String userAgent, @HeaderParam(Const.LOCATION) String location,
			@PathParam(Const.SESSION_TOKEN) String sessionToken) {
		Response response = null;
		if (sessionMid.sessionTokenExists(sessionToken)) {
			String userId = sessionMid.getUserIdUsingSessionToken(sessionToken);
			if (!sessionMid.checkAppForToken(sessionToken, appId))
				return Response.status(Status.UNAUTHORIZED).entity(new Error("Action in wrong app: "+appId)).build();
			if (location != null) {
				Metadata meta = usersMid.updateMetadata(appId, userId, null, userId, ModelEnum.users, location);
				Result res = new Result("Refresh OK", meta);
				sessionMid.refreshSession(sessionToken, location, userAgent);					
				response = Response.status(Status.OK).entity(res).build();
			} // if the device does not have the gps turned on we should not
			// refresh the session.
			// only refresh it when an action is performed.

			Response.status(Status.NOT_FOUND).entity(new Error("SessionToken: "+sessionToken)).build();
		} else
			response = Response.status(Status.FORBIDDEN).entity(new Error("You do not have permission to access.")).build();
		return response;
	}


	// *** DELETE *** //

	/**
	 * Deletes a session (signout).
	 * 
	 * @param sessionToken
	 * @return
	 */
	@Consumes({ MediaType.APPLICATION_JSON })
	@Produces({ MediaType.APPLICATION_JSON })
	@POST
	@Path("/signout/{sessionToken}")
	public Response deleteSession(JSONObject inputJsonObj, @PathParam(Const.SESSION_TOKEN) String sessionToken) {
		Response response = null;
		Boolean flagAll = (Boolean) inputJsonObj.opt("all");
		String userId = sessionMid.getUserIdUsingSessionToken(sessionToken);
		if(userId!=null){
			if (sessionMid.sessionTokenExists(sessionToken)) {
				if(!flagAll){
					if (!sessionMid.checkAppForToken(sessionToken, appId))
						return Response.status(Status.UNAUTHORIZED).entity(new Error("Action in wrong app: "+appId)).build();
					//deletes the sessions user with the token = sessionToken
					if (sessionMid.deleteUserSession(sessionToken, userId)){
						Metadata meta = usersMid.updateMetadata(appId, userId, null, userId, ModelEnum.users, null);
						Result res = new Result("Signout OK", meta);
						response = Response.status(Status.OK).entity(res).build();
					}
					else{
						response = Response.status(Status.NOT_FOUND).entity(new Error("Not found")).build();
					}
				}else{
					if (!sessionMid.checkAppForToken(sessionToken, appId))
						return Response.status(Status.UNAUTHORIZED).entity(new Error("Action in wrong app: "+appId)).build();
					//deletes all sessions user
					Log.debug("", this, "deleteSession", "********DELETING ALL SESSIONS FOR THIS USER");
					boolean sucess = sessionMid.deleteAllUserSessions(userId);
					if (sucess){
						Metadata meta = usersMid.updateMetadata(appId, userId, null, userId, ModelEnum.users, null);
						Result res = new Result("Signout OK", meta);
						response = Response.status(Status.OK).entity(res).build();
					}
					else
						response = Response.status(Status.NOT_FOUND).entity(new Error("No sessions exist")).build();
				} 
			}
		}
		else 
			response = Response.status(Status.FORBIDDEN).entity(new Error("FORBIDDEN")).build();		
		return response;
	}


	// *** GET LIST *** //


	// *** GET *** //

	/**
	 * Gets the session fields associated with thif (!sessionMid.checkAppForToken(sessionToken, appId))
				return Response.status(Status.UNAUTHORIZED).entity(new Error("Action in wrong app: "+appId)).build();e token.
	 * 
	 * @param sessionToken
	 * @return
	 */
	@GET
	@Path("/sessions/{sessionToken}")
	public Response getUserIdWithSession(
			@PathParam(Const.SESSION_TOKEN) String sessionToken) {
		Response response = null;
		if (sessionMid.sessionTokenExists(sessionToken)) {
			String userId = sessionMid.getUserIdUsingSessionToken(sessionToken);
			if (!sessionMid.checkAppForToken(sessionToken, appId))
				return Response.status(Status.UNAUTHORIZED).entity(new Error("Action in wrong app: "+appId)).build();
			Metadata meta = usersMid.getMetadata(appId, userId, null, ModelEnum.users);
			Result res = new Result("OK", meta);
			response = Response.status(Status.OK).entity(res).build();
		} else
			response = Response.status(Status.NOT_FOUND).entity(new Error(sessionToken)).build();
		return response;
	}

	/**@HeaderParam(value = Const.LOCATION) String location
	 * Gets the session fields associated with the token.
	 * 
	 * @param sessionToken
	 * @return
	 */
	@GET
	@Path("/sessions")
	public Response getSessionFields(
			@PathParam(Const.SESSION_TOKEN) String sessionToken) {
		Response response = null;
		if (sessionMid.sessionTokenExists(sessionToken)) {
			String userId = sessionMid.getUserIdUsingSessionToken(sessionToken);
			if (!sessionMid.checkAppForToken(sessionToken, appId))
				return Response.status(Status.UNAUTHORIZED).entity(new Error("Action in wrong app: "+appId)).build();
			User outUser = usersMid.getUserInApp(appId, userId);
			Metadata meta = usersMid.getMetadata(appId, userId, null, ModelEnum.users);
			Result res = new Result(outUser, meta);
			response = Response.status(Status.OK).entity(res).build();
		} else
			response = Response.status(Status.NOT_FOUND).entity(new Error("Token NOT_FOUND")).build();
		return response;
	}


	// *** OTHERS *** //

	@POST
	@Path("/recovery")
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response makeRecoveryRequest(JSONObject inputJson, @Context UriInfo ui, @Context HttpHeaders hh,
			@HeaderParam(value = Const.LOCATION) String location, @HeaderParam(value = Const.APP_KEY) String appKey){
		Response response = null;
		String email = null;
		String newPass = Utils.getRandomString(Const.getPasswordLength());
		byte[] salt = null;
		byte[] hash = null;
		try {
			email = (String) inputJson.get("email");
		} catch (JSONException e) {
			Log.error("", this, "makeRecoveryRequest", "Error parsing the JSON.", e); 
		}
		PasswordEncryptionService service = new PasswordEncryptionService();
		try {
			salt = service.generateSalt();
			hash = service.getEncryptedPassword(newPass, salt);
		} catch (NoSuchAlgorithmException e) {
			Log.error("", this, "makeRecoveryRequest", "Hashing Algorithm failed, please review the PasswordEncryptionService.", e); 
		} catch (InvalidKeySpecException e) {
			Log.error("", this, "makeRecoveryRequest", "Invalid Key.", e); 
		}
		String userId = usersMid.getUserIdUsingEmail(appId, email);
		if(userId==null)
			return Response.status(Status.BAD_REQUEST).entity(new Error("Wrong email.")).build();
		if(appKey==null)
			return Response.status(Status.BAD_REQUEST).entity("App Key not found").build();
		if(!appsMid.authenticateApp(appId,appKey))
			return Response.status(Status.UNAUTHORIZED).entity("Wrong App Key").build();
		boolean opOk = usersMid.recoverUser(appId, userId, email, ui, newPass,hash,salt);
		if(opOk){
			Result res = new Result("Email sent with recovery details.", null);
			response = Response.status(Status.OK).entity(res).build();
		}
		else
			response = Response.status(Status.BAD_REQUEST).entity(new Error("Wrong email.")).build();
		return response;

	}

	@POST
	@Path("/changepassword")
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response changePasswordRequest(JSONObject inputJsonObj, @Context UriInfo ui, @Context HttpHeaders hh){
		Response response = null;
		MultivaluedMap<String, String> headerParams = hh.getRequestHeaders();
		String oldPassword = null;
		String newPassword = null; 
		List<String> locationList = null;
		List<String> userAgentList = null;
		String userAgent = null;
		String location = null;
		try {
			newPassword = (String) inputJsonObj.get("newPassword");
			oldPassword = (String) inputJsonObj.get("oldPassword");
		} catch (JSONException e) {
			Log.error("", this, "createSession", "Error parsing the JSON.", e); 
			return Response.status(Status.BAD_REQUEST).entity(new Error("Error reading JSON")).build();
		}
		for (Entry<String, List<String>> entry : headerParams.entrySet()) {
			if (entry.getKey().equalsIgnoreCase(Const.LOCATION))
				locationList = entry.getValue();
			if (entry.getKey().equalsIgnoreCase("user-agent")){
				userAgentList = entry.getValue();
			}
		}

		if (userAgentList != null)
			userAgent = userAgentList.get(0);
		if (locationList != null)
			location = locationList.get(0);
		try{
			String sessionToken = Utils.getSessionToken(hh);
			String userId = sessionMid.getUserIdUsingSessionToken(sessionToken);
			if (sessionMid.checkAppForToken(Utils.getSessionToken(hh), appId))
				return Response.status(Status.UNAUTHORIZED).entity(new Error("Action in wrong app: "+appId)).build();
			Boolean auth = sessionMid.authenticateUser(appId, userId, oldPassword);
			if(auth){
				usersMid.updateUserPassword(appId, userId, newPassword);
				if(location!=null)
					sessionMid.refreshSession(sessionToken, location, userAgent);
				response = Response.status(Status.OK).entity("Passoword correctly changed.").build();
			}else
				response = Response.status(Status.BAD_REQUEST).entity(new Error("Wrong old password.")).build();
		}catch (Exception e) {
			return Response.status(Status.INTERNAL_SERVER_ERROR).entity(new Error("INTERNAL_SERVER_ERROR")).build();
		}
		return response;

	}


	// *** RESOURCES *** //

	/**
	 * Launches the resource integration requests.
	 * 
	 * @param appId
	 * @return
	 */
	@Path("integration")
	public IntegrationResource integration() {
		try {
			return new IntegrationResource(appId);
		} catch (IllegalArgumentException e) {
			Log.error("", this, "integration", "Illegal Argument.", e); 
			throw new WebApplicationException(Response.status(Status.BAD_REQUEST).entity(new Error("Parse error")).build());
		}
	}
}
