package infosistema.openbaas.rest;

import infosistema.openbaas.middleLayer.SessionMiddleLayer;
import infosistema.openbaas.middleLayer.UsersMiddleLayer;
import infosistema.openbaas.middleLayer.MiddleLayerFactory;
import infosistema.openbaas.rest.AppsResource.PATCH;
import infosistema.openbaas.utils.Const;
import infosistema.openbaas.utils.Utils;

import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.Consumes;
import javax.ws.rs.CookieParam;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.NewCookie;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;

import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;


//@Path(/users/{userId}/sessions)
public class SessionsResource {
	private static final int IDGENERATOR = 3;
	private static final Utils utils = new Utils();
	private UsersMiddleLayer usersMid;
	private SessionMiddleLayer sessionMid;
	private String appId;
	private String userId;
	

	@Context
	UriInfo uriInfo;

	public SessionsResource(String appId, String userId) {
		this.usersMid = MiddleLayerFactory.getUsersMiddleLayer();
		this.sessionMid = MiddleLayerFactory.getSessionMiddleLayer();
		this.appId = appId;
		this.userId = userId;
	}

	/**
	 * Creates a user session and returns de session Identifier (generated by
	 * the server). Required fields: "userName", "password".
	 * 
	 * @param req
	 * @param inputJsonObj
	 * @return
	 */
	@POST
	@Consumes({ MediaType.APPLICATION_JSON })
	@Produces({ MediaType.APPLICATION_JSON })
	public Response createSession(@Context HttpServletRequest req,
			JSONObject inputJsonObj, @Context UriInfo ui, @Context HttpHeaders hh) {
		String userName = null; // user inserted fields
		String attemptedPassword = null; // user inserted fields
		Response response = null;
		try {
			userName = (String) inputJsonObj.get("userName");
			attemptedPassword = (String) inputJsonObj.get("password");
		} catch (JSONException e) {
			System.out.println("Error Reading the jsonFile");
			return Response.status(Status.BAD_REQUEST).entity("Error reading JSON").build();
		}
		if(userName == null && attemptedPassword == null)
			return Response.status(Status.BAD_REQUEST).entity("Error reading JSON").build();
		String userId = usersMid.getUserIdUsingUserName(appId, userName);
		if (userId != null) {
			boolean usersConfirmedOption = usersMid.confirmUsersEmailOption(appId);
			// Remember the order of evaluation in java
			if (usersConfirmedOption) {
				if (usersMid.userEmailIsConfirmed(appId, userId)) {
					System.out.println("userId of " + userName + " is: " + userId);
					String sessionToken = utils.getRandomString(IDGENERATOR);
					boolean validation = sessionMid.createSession(sessionToken, appId, userId, attemptedPassword);
					if (validation) {
						NewCookie identifier = new NewCookie("sessionToken", sessionToken);

						response = Response.status(Status.OK).entity(identifier).build();
					}
					response = Response.status(Status.OK).entity(sessionToken).build();
				} else {
					response = Response.status(Status.FORBIDDEN).entity(Const.EMAIL_CONFIRMATION_ERROR).build();
				}
			} else
				response = Response.status(Status.UNAUTHORIZED).entity("").build();
		} else
			response = Response.status(Status.NOT_FOUND).entity("").build();
		return response;

	}

	/**
	 * Deletes a session (logout).
	 * 
	 * @param sessionToken
	 * @return
	 */
	@DELETE
	@Path("{sessionToken}")
	public Response deleteSession(@PathParam("sessionToken") String sessionToken) {
		Response response = null;
		if (sessionMid.deleteUserSession(sessionToken, userId))
			response = Response.status(Status.OK).entity(sessionToken).build();
		else
			response = Response.status(Status.NOT_FOUND).entity(sessionToken).build();
		return response;
	}

	/**
	 * Gets the session fields associated with the token.
	 * 
	 * @param sessionToken
	 * @return
	 */
	@GET
	@Path("{sessionToken}")
	public Response getSessionFields(
			@PathParam("sessionToken") String sessionToken,
			@CookieParam(value = "sessionToken") String sessionTokenCookie) {
		Response response = null;
		if (sessionMid.sessionTokenExists(sessionTokenCookie)) {
			response = Response.status(Status.OK).entity(sessionToken).build();
		} else
			response = Response.status(Status.NOT_FOUND).entity(sessionToken).build();
		return response;
	}

	/**
	 * Deletes all the sessions of the user (a user can have more than one
	 * session, one for chrome, another for iphone, ect).
	 * 
	 * @return
	 */
	@DELETE
	@Path("/all")
	public Response deleteAllSessions(@CookieParam(value = "sessionToken") String sessionToken) {
		Response response = null;
		if (sessionMid.sessionTokenExists(sessionToken)) {
			System.out.println("************************************");
			System.out.println("********DELETING ALL SESSIONS FOR THIS USER");
			boolean sucess = sessionMid.deleteAllUserSessions(userId);
			if (sucess)
				response = Response.status(Status.OK).entity(userId).build();
			else
				response = Response.status(Status.NOT_FOUND).entity("No sessions exist").build();
		} else
			response = Response.status(Status.FORBIDDEN).entity("").build();

		return response;
	}

	@PATCH
	@Path("{sessionToken}")
	@Consumes({ MediaType.APPLICATION_JSON })
	public Response patchSession(
			@HeaderParam("user-agent") String userAgent,
			@HeaderParam("location") String location,
			@PathParam("sessionToken") String sessionToken,
			@CookieParam(value = "sessionToken") String sessionTokenCookie) {
		Response response = null;
		if (sessionMid.sessionTokenExists(sessionToken)) {
			if (sessionMid.sessionExistsForUser(userId)) {
				if (location != null) {
					sessionMid.refreshSession(sessionToken, location, userAgent);
					response = Response.status(Status.OK).entity("").build();
				} // if the device does not have the gps turned on we should not
					// refresh the session.
					// only refresh it when an action is performed.
			}
			Response.status(Status.NOT_FOUND).entity(sessionToken).build();
		} else
			response = Response.status(Status.FORBIDDEN).entity("You do not have permission to access.").build();
		return response;
	}
}
